### ISSUE TITLE
feat: autopeek in cursor moving

### ISSUE THREAD

**Issue by icristianhernandez** [oskarrrrrrr/symbols.nvim#1]
Exactly as the title says.

Maybe is it possible to extend the current configuration with an autocmd to achieve this?

**Comment by icristianhernandez** [comment]
Perhaps this feature could be extended to include an additional configuration flag that enables auto-preview by default. While the ability to enable this on the fly is convenient, some users may prefer to have auto-preview always active (automating the initial `tp` command in each session).

**Comment by oskarrrrrrr** [comment]
Okay, I can add this. We will have a setting and a toggle for auto peek on cursor move and a setting for auto preview.

Other plugins also have movements with peek - <C-j> and <C-k> to move up and down and peek. Not sure if that's useful.

**Comment by oskarrrrrrr** [comment]
auto peek: 6eb6df48f29bc9feaa3d29adea3a87ae5f567f41
auto preview: b074b9343ab801d1e3c8ce9fdd3cf521750670d7
