### ISSUE TITLE
attempt to index global ' selection_range' (a nil value) 

### ISSUE THREAD

**Issue by Chakotay** [oskarrrrrrr/symbols.nvim#10]
Great outline/symbols plugin!. The plugin was working perfectly yesterday after installation but is now failing for no apparent reason: the preview ('K') throws this message:

E5108: Error executing lua: ....local/share/nvim/lazy/symbols.nvim/lua/symbols/init.lua:178: attempt to index global ' selection_range' (a nil value)                                                                                        
stack traceback:                                                                                                      
....local/share/nvim/lazy/symbols.nvim/lua/symbols/init.lua:178: in function 'open'                                   ....local/share/nvim/lazy/symbols.nvim/lua/symbols/init.lua:1958: in function <....local/share/nvim/lazy/symbols.nvim/lua/symbols/init.lua:1957>                                                                                    

Plugin hydra was installed after Symbols, but removing it did not fix the pb. Removed share/nvim and  state/nvim folders, and reinstalled everything, but problem remains.  Any idea? thanks

**Comment by oskarrrrrrr** [comment]
Thanks for catching that. I was doing some refactoring and missed it, should be working now

**Comment by Chakotay** [comment]
Thanks, works great! Again great symbols plugin!

**Comment by oskarrrrrrr** [comment]
Thanks, appreciate it 😊
